// <auto-generated />
using System;
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250425182543_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Kund", b =>
                {
                    b.Property<int>("Kundnummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kundnummer"));

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kundnummer");

                    b.ToTable("Kunder");

                    b.HasData(
                        new
                        {
                            Kundnummer = 1,
                            Namn = "Kund Kundsson",
                            Telefonnummer = "0123456789"
                        });
                });

            modelBuilder.Entity("Data.Models.Projekt", b =>
                {
                    b.Property<int>("Projektnummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Projektnummer"));

                    b.Property<int>("AntalTimmar")
                        .HasColumnType("int");

                    b.Property<int>("Kundnummer")
                        .HasColumnType("int");

                    b.Property<int>("Kundnummer1")
                        .HasColumnType("int");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Projektansvarig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Slutdatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TjanstId")
                        .HasColumnType("int");

                    b.Property<decimal>("Totalpris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Projektnummer");

                    b.HasIndex("Kundnummer1");

                    b.HasIndex("TjanstId");

                    b.ToTable("Projekt");
                });

            modelBuilder.Entity("Data.Models.Tjanst", b =>
                {
                    b.Property<int>("TjanstId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TjanstId"));

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrisPerTimme")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TjanstId");

                    b.ToTable("Tjanster");

                    b.HasData(
                        new
                        {
                            TjanstId = 1,
                            Namn = "IT-konsult",
                            PrisPerTimme = 1000m
                        },
                        new
                        {
                            TjanstId = 2,
                            Namn = "HR-konsult",
                            PrisPerTimme = 2000m
                        });
                });

            modelBuilder.Entity("Data.Models.Projekt", b =>
                {
                    b.HasOne("Data.Models.Kund", "Kund")
                        .WithMany("Projekt")
                        .HasForeignKey("Kundnummer1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Tjanst", "Tjanst")
                        .WithMany("Projekt")
                        .HasForeignKey("TjanstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kund");

                    b.Navigation("Tjanst");
                });

            modelBuilder.Entity("Data.Models.Kund", b =>
                {
                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("Data.Models.Tjanst", b =>
                {
                    b.Navigation("Projekt");
                });
#pragma warning restore 612, 618
        }
    }
}
